SCORE/Models/Exercicio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SCORE.Models;

[Table("Exercicio")]
public partial class Exercicio
{

    [Key]
    [Column("Id_Exercicio")]
    public int IdExercicio { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }
  
    public int? Nota { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataEntrega { get; set; }

    [InverseProperty("IdExercicioNavigation")]
    public virtual ICollection<ExercicioUc> ExercicioUcs { get; } = new List<ExercicioUc>();
}

SCORE/Controllers/ExerciciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using SCORE.Data;
using SCORE.Models;

namespace SCORE.Controllers
{
    public class ExerciciosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostEnvironment _he;

        public ExerciciosController(ApplicationDbContext context, IHostEnvironment e)
        {
            _context = context;
            _he = e;
        }

        //[Authorize(Roles = "Docente")]
        public async Task<IActionResult> Index()
        {

            var applicationDbContext = _context.Exercicios;
            return View(await applicationDbContext.ToListAsync());
        }



        public List<FileViewModel> GetFiles(string he, string utilizador)
        {
            List<FileViewModel> arquivos = new List<FileViewModel>();

            string caminho = Path.Combine("C:\\Users\\pedro\\Desktop\\UTAD\\3º Ano\\2ºSemestre\\Lab Projeto\\SCORE\\SCORE\\wwwroot\\Documents\\", he);

            // Verifica se o diretório existe antes de tentar ler os arquivos
            if (Directory.Exists(caminho))
            {
                // Obtém os nomes dos arquivos no diretório
                string[] nomesArquivos = Directory.GetFiles(caminho);

                // Cria um objeto FileViewModel para cada arquivo e adiciona à lista
                foreach (string nomeArquivo in nomesArquivos)
                {
                    var arquivo = new FileViewModel { Name = Path.GetFileName(nomeArquivo), Nota = 0, Utilizador = utilizador };
                    _context.Add(arquivo);
                    arquivos.Add(arquivo);
                }
                _context.SaveChanges();
            }

            return arquivos;
        }

        //[Authorize(Roles = "Docente")]
        public async Task<IActionResult> AtualizarNota(string nomeArquivo, int nota)
        {
            var arquivo = await _context.Exercicios.FirstOrDefaultAsync(a => a.Titulo == nomeArquivo);

            if (arquivo != null)
            {
                arquivo.Nota = nota;
                _context.Update(arquivo);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Submissoes));
        }



        // GET
        //[Authorize(Roles = "Docente")]

        [Route("Exercicios/Submissoes")]
        public async Task<IActionResult> Submissoes(int id, int nota)
        {
            DocFiles files = new DocFiles();

            string utilizador = User.Identity.Name;

            ViewBag.xpto = files.GetFiles(_he, User.Identity.Name).Count();



            return View(files.GetFiles(_he, User.Identity.Name));

        }


        // GET: Exercicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Exercicios == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios
                .FirstOrDefaultAsync(m => m.IdExercicio == id);
            if (exercicio == null)
            {
                return NotFound();
            }

            return View(exercicio);
        }


        public IActionResult Upload()
        {
            return View();
        }

        // GET: Exercicios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Exercicios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdExercicio,Titulo,Descricao,Nota,DataEntrega")] Exercicio exercicio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exercicio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(exercicio);
        }

        // GET: Exercicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Exercicios == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios.FindAsync(id);
            if (exercicio == null)
            {
                return NotFound();
            }
            return View(exercicio);
        }

        // POST: Exercicios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdExercicio,Titulo,Descricao,Nota,DataEntrega")] Exercicio exercicio)
        {
            if (id != exercicio.IdExercicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exercicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExercicioExists(exercicio.IdExercicio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(exercicio);
        }



        // GET: Exercicios/Delete/5
        //[Authorize(Roles = "Docente")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Exercicios == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios
                .FirstOrDefaultAsync(m => m.IdExercicio == id);
            if (exercicio == null)
            {
                return NotFound();
            }

            return View(exercicio);
        }




        // POST: Exercicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Exercicios == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Exercicios'  is null.");
            }
            var exercicio = await _context.Exercicios.FindAsync(id);
            if (exercicio != null)
            {
                _context.Exercicios.Remove(exercicio);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Upload(IFormFile Name)
        {
            if (ModelState.IsValid)
            {
                string destination = Path.Combine(
                    _he.ContentRootPath, "wwwroot/Documents", Path.GetFileName(Name.FileName)
                    );

                FileStream fs = new FileStream(destination, FileMode.Create);

                Name.CopyTo(fs);
                fs.Close();

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Download(string id)
        {
            string pathFile = Path.Combine(_he.ContentRootPath, "wwwroot/Documents/", id);

            byte[] fileBytes = System.IO.File.ReadAllBytes(pathFile);

            string mimeType;

            new FileExtensionContentTypeProvider().TryGetContentType(id, out mimeType);

            return File(fileBytes, mimeType);

        }

        private bool ExercicioExists(int id)
        {
            return (_context.Exercicios?.Any(e => e.IdExercicio == id)).GetValueOrDefault();
        }
    }
}

SCORE/Views/Exercicios/Create.cshtml
@model SCORE.Models.Exercicio
@{
    ViewData["Title"] = "Create";
}

<h1>Criar Exercício</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label text-white">Unidade curricular</label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label text-white">Descrição</label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="Tipo" class="control-label text-white"></label>
            <input asp-for="Tipo" class="form-control" />
            <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
            <label asp-for="Nota" class="control-label text-white"></label>
            <input asp-for="Nota" class="form-control" />
            <span asp-validation-for="Nota" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="DataEntrega" class="control-label text-white">Data de Entrega</label>
                <input asp-for="DataEntrega" class="form-control" />
                <span asp-validation-for="DataEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="text-white">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}




@*
<hr />

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<ExercicioTipo>()" > 
                    <option value="">--Select type--</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Questions</label>
                <div id="questions-container">
                    <div class="question-item">
                        <div class="form-group">
                            <label>Question</label>
                            <input type="text" class="form-control question-text" />
                        </div>
                        <div class="form-group" style="display:none;">
                            <label>Type</label>
                            <input type="text" class="form-control question-type" />
                        </div>
                        <div class="form-group options-group" style="display:none;">
                            <label>Options</label>
                            <div class="option-items"></div>
                            <button type="button" class="btn btn-primary add-option">Add Option</button>
                        </div>
                        <div class="form-group file-group" style="display:none;">
                            <label>File Submission</label>
                            <input type="file" class="form-control file-input" />
                        </div>
                        <div class="form-group open-response-group" style="display:none;">
                            <label</label>
                            <textarea class="form-control open-response"></textarea>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-primary add-question">Add Question</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('.add-question').click(function () {
                var $template = $('.question-item').first().clone();
                $template.find('.question-text').val('');
                $template.find('.question-type').val($('#Type').val());
                $template.find('.option-items').empty();
                $template.find('.file-input').val('');
                $template.find('.open-response').val('');
                if ($('#Type').val() === 'MultipleChoice') {
                    $template.find('.options-group').show();
                    $template.find('.option-items').empty();
                    $template.find('.option-items').append($('<div class="option-item"><input type="text" class="form-control option-text" /><button type="button" class="btn btn-danger remove-option">Remove</button></div>'));
                    $('.add-option').click(function () {
                        var $template = $('<div class="option-item"><input type="text" class="form-control option-text" /><button type="button" class="btn btn-danger remove-option">Remove</button></div>');
                        $template.appendTo($(this).closest('.question-item').find('.option-items'));
                    });

                }
                      } else if ($('#Type').val() === 'FileSubmission') {
                        $template.find('.file-group').show();
                    } else if ($('#Type').val() === 'OpenResponse') {
                        $template.find('.open-response-group').show();
                    }
                $template.appendTo('#questions-container');
            });

            $('.add-option').click(function () {
                var $template = $('<div class="option-item"><input type="text" class="form-control option-text" /><button type="button" class="btn btn-danger remove-option">Remove</button></div>');
                $template.appendTo($(this).prev('.option-items'));
            });

            $(document).on('click', '.remove-option', function () {
                $(this).parent('.option-item').remove();
            });
        });
    </script>
}

*@




@*@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Exercicio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota" class="control-label"></label>
                <input asp-for="Nota" class="form-control" />
                <span asp-validation-for="Nota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataEntrega" class="control-label"></label>
                <input asp-for="DataEntrega" class="form-control" />
                <span asp-validation-for="DataEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

SCORE/Views/Exercicios/Delete.cshtml
@model SCORE.Models.Exercicio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exercicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataEntrega)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdExercicio" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SCORE/Views/Exercicios/Details.cshtml
@model SCORE.Models.Exercicio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Exercicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataEntrega)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdExercicio">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SCORE/Views/Exercicios/Edit.cshtml
@model SCORE.Models.Exercicio

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-white">Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdExercicio" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label text-white"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger text-white"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label text-white"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger text-white"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataEntrega" class="control-label text-white"></label>
                <input asp-for="DataEntrega" class="form-control" />
                <span asp-validation-for="DataEntrega" class="text-danger text-white"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="text-white">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SCORE/Views/Exercicios/Index.cshtml
@model IEnumerable<SCORE.Models.Exercicio>

@{
    ViewData["Title"] = "Index";
}

<h1>Exercícios</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Criar Novo Exercício</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Unidade Curricular
            </th>
            <th>
                Descrição
            </th>
            <th>
                Data de Entrega
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEntrega)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdExercicio" class="btn btn-secondary">Edit</a>
                    @*<a asp-action="Details" asp-route-id="@item.IdExercicio">Details</a> |*@
                    <a asp-controller="Exercicios" asp-action="Submissoes" class="btn btn-secondary">Submissões</a>
                    <a asp-action="Upload" class="btn btn-secondary">Submeter</a>
                    <a asp-action="Delete" asp-route-id="@item.IdExercicio" class="btn btn-danger">Delete</a>
            </tr>
        }
    </tbody>
</table>

<style>
    .table {
        border-bottom: none;
    }
</style>

SCORE/Views/Exercicios/Submissoes.cshtml
@model IEnumerable<SCORE.Models.FileViewModel>

@{
    ViewData["Title"] = "Submissões";
}

<h1 class="text-white">Submissões</h1>

<div class="nota-aviso">
    As notas devem ser atribuídas de 0 a 5.
</div>

<table class="table table-borderless">
    <thead>
        <tr>
            <th>
                Nome do Ficheiro
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <div class="nota-container" data-item-name="@item.Name">
                        @Html.DisplayFor(modelItem => item.Nota)
                    </div>
                </td>
                <td>
                    @using (Html.BeginForm("SetNota", "Exercicios", new { id = item.Name }))
                    {
                        <div class="form-group">
                            <div class="col-md-4">
                                @Html.TextBoxFor(modelItem => item.Nota, new { @class = "form-control nota-input", data_item_name = item.Name })
                            </div>
                            <div class="col-md-2">
                                <input type="submit" value="Atribuir Nota" class="btn btn-primary submit-nota" />
                            </div>
                        </div>
                    }
                </td>
                <td>
                    <div class="text-center">
                        <a asp-controller="Exercicios" asp-action="Download" asp-route-id="@item.Name" class="btn btn-secondary" target="_blank">Download</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    <script>
        $(document).ready(function () {
            // Armazena a nota original em um objeto de dados na div de contêiner
            $(".nota-container").each(function () {
                var nota = $(this).text();
                $(this).data("original-nota", nota);
            });

            // Manipula o evento de envio do formulário
            $(".submit-nota").click(function (e) {
                e.preventDefault();

                var form = $(this).closest("form");
                var notaInput = form.find(".nota-input");
                var notaContainer = form.closest("tr").find(".nota-container");

                // Obtém a nota atualizada do campo de entrada
                var novaNota = notaInput.val();

                // Verifica se a nova nota é válida
                if (novaNota > 5) {
                    alert("Nota inválida! Insira um valor de 0 a 5.");
                    return;
                }

                // Atualiza a nota na div de contêiner
                notaContainer.text(novaNota);

                // Armazena a nova nota em um objeto de dados na div de contêiner
                notaContainer.data("nova-nota", novaNota);

                // Desativa o campo de entrada
                notaInput.prop("disabled", true);

                // Desativa o botão de envio
                $(this).prop("disabled", true);
            });

            // Restaura a nota original ao fechar a sessão
            $(window).on("beforeunload", function () {
                $(".nota-container").each(function () {
                    var notaContainer = $(this);
                    var notaOriginal = notaContainer.data("original-nota");
                    notaContainer.text(notaOriginal);
                });
            });
        });
    </script>
}




@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Name">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Name">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Name">Delete</a>
                    <a asp-controller="Exercicios" asp-action="Download" asp-route-id=@item.Name target="_blank">Download</a>
                </td>
            </tr>
        }
    </tbody>
</table>
*@

SCORE/Views/Exercicios/Upload.cshtml
@model SCORE.Models.FileViewModel

@{
    ViewData["Title"] = "Upload";
}

<h1 class="text-white">Submeter</h1>

<div class="nota-aviso">
    Todos os ficheiros devem ser devidamente identificados pelo aluno
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label text-white"></label>
                <input asp-for="Name" type="file" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="text-white">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}